use super::Report;

pub fn format(report: &Report) -> String {
    let mut out = String::new();

    out.push_str(&format!("# Gitinspector Report: {}\n\n", report.repo_name));
    out.push_str(&format!("- **Branch:** `{}`\n", report.branch_name));
    if let Some(url) = &report.remote_url {
        out.push_str(&format!("- **Remote:** [{}]({})\n", url, url));
    }
    out.push_str(&format!("- **Analysis Date:** {}\n\n", chrono::Local::now().format("%Y-%m-%d %H:%M:%S")));

    out.push_str("## 📊 Author Statistics\n\n");
    out.push_str("| Author | Commits | Insertions | Deletions | Impact |\n");
    out.push_str("| :--- | :---: | :---: | :---: | :---: |\n");
    for stat in &report.authors {
        out.push_str(&format!(
            "| **{}** | {} | `+ {}` | `- {}` | {} net |\n",
            stat.name,
            stat.commits,
            stat.insertions,
            stat.deletions,
            stat.insertions + stat.deletions
        ));
    }
    out.push_str("\n");

    if let Some(timeline) = &report.timeline {
        out.push_str("## 📈 Activity Velocity\n\n");
        out.push_str("| Period | Commits | Insertions | Deletions |\n");
        out.push_str("| :--- | :---: | :---: | :---: |\n");
        // Show last 20 periods for brevity in markdown
        let start = if timeline.len() > 20 { timeline.len() - 20 } else { 0 };
        for period in &timeline[start..] {
            out.push_str(&format!(
                "| {} | {} | {} | {} |\n",
                period.period_name, period.commits, period.insertions, period.deletions
            ));
        }
        out.push_str("\n");
    }

    if let Some(blame) = &report.blame {
        out.push_str("## 🔍 Author Responsibilities (Drill-down)\n\n");
        for stat in blame {
            out.push_str(&format!("### {} ({} lines owned)\n\n", stat.author_name, stat.lines));
            out.push_str("| File Path | Lines |\n");
            out.push_str("| :--- | :---: |\n");
            for file in &stat.top_files {
                let file_link = if let Some(url) = &report.remote_url {
                    format!("[`{}`]({}/blob/master/{})", file.path, url, file.path)
                } else {
                    format!("`{}`", file.path)
                };
                out.push_str(&format!("| {} | **{}** |\n", file_link, file.lines));
            }
            out.push_str("\n");
        }
    }

    if let Some(health) = &report.health {
        out.push_str("## 🏥 Repository Health\n\n");
        out.push_str(&format!("- **Total Branches:** {}\n", health.active_branches.len()));
        out.push_str(&format!("- **Stale Branches:** {} (Inactive >90 days)\n", health.stale_branches_count));
        out.push_str(&format!("- **Estimated PRs:** {}\n\n", health.estimated_prs_count));
    }

    out.push_str("## 📁 File Hotspots (Top Changes)\n\n");
    out.push_str("| File Path | Commits | LOC | Size (KB) | Last Update |\n");
    out.push_str("| :--- | :---: | :---: | :---: | :---: |\n");
    for file in report.file_stats.iter().take(20) {
        let file_link = if let Some(url) = &report.remote_url {
            format!("[`{}`]({}/blob/{}/{})", file.path, url, report.branch_name, file.path)
        } else {
            format!("`{}`", file.path)
        };
        out.push_str(&format!(
            "| {} | **{}** | {} | {:.1} | {} |\n",
            file_link, file.commits, file.loc, file.total_lines as f32 / 1024.0, file.last_updated
        ));
    }
    out.push_str("\n");

    out.push_str(&format!("---\n*Generated by [gitinspector-rs](https://github.com/softmentor/gitinspector-rs) v{} in {}*\n", report.version, report.duration));

    out
}
