use super::Report;

pub fn format(report: &Report) -> String {
    let mut out = String::new();
    
    out.push_str(&format!("Repository: {}\n", report.repo_name));
    out.push_str(&format!("Branch:     {}\n", report.branch_name));
    if let Some(url) = &report.remote_url {
        out.push_str(&format!("Remote:     {}\n", url));
    }
    out.push_str(&format!("Found {} authors.\n\n", report.authors.len()));
    
    out.push_str(&format!("{:<25} | {:>10} | {:>15} | {:>15}\n", "Author", "Commits", "Insertions", "Deletions"));
    out.push_str(&format!("{:-<25}-|-{:-<10}-|-{:-<15}-|-{:-<15}\n", "", "", "", ""));
    for stat in &report.authors {
        out.push_str(&format!("{:<25} | {:>10} | {:>15} | {:>15}\n", stat.name, stat.commits, stat.insertions, stat.deletions));
    }
    out.push('\n');

    if let Some(timeline) = &report.timeline {
        out.push_str("--- Timeline ---\n");
        out.push_str(&format!("{:<10} | {:>10} | {:>10} | {:>10}\n", "Period", "Commits", "Insertions", "Deletions"));
        out.push_str(&format!("{:-<10}-|-{:-<10}-|-{:-<10}-|-{:-<10}\n", "", "", "", ""));
        for period in timeline {
            out.push_str(&format!("{:<10} | {:>10} | {:>10} | {:>10}\n", period.period_name, period.commits, period.insertions, period.deletions));
        }
        out.push('\n');
    }

    if let Some(blame) = &report.blame {
        out.push_str("--- Blame Responsibilities ---\n");
        for stat in blame {
            out.push_str(&format!("\n{} ({} lines)\n", stat.author_name, stat.lines));
            for file in &stat.top_files {
                out.push_str(&format!("  {:<40} | {:>10}\n", file.path, file.lines));
            }
        }
        out.push('\n');
    }

    if !report.file_stats.is_empty() {
        out.push_str("--- Hotspots (High Activity Files) ---\n");
        out.push_str(&format!("{:<40} | {:>7} | {:>10} | {:>10}\n", "Path", "Commits", "LOC", "Size (KB)"));
        out.push_str(&format!("{:-<40}-|-{:-<7}-|-{:-<10}-|-{:-<10}\n", "", "", "", ""));
        for stat in report.file_stats.iter().take(10) {
            out.push_str(&format!("{:<40} | {:>7} | {:>10} | {:>10.1}\n", 
                stat.path, stat.commits, stat.loc, stat.total_lines as f32 / 1024.0));
        }
        out.push('\n');
    }

    if let Some(health) = &report.health {
        out.push_str("--- Repository Health ---\n");
        out.push_str(&format!("Total Branches:  {}\n", health.active_branches.len()));
        out.push_str(&format!("Stale Branches:  {} (Inactive >90 days)\n", health.stale_branches_count));
        out.push_str(&format!("Estimated PRs:   {}\n", health.estimated_prs_count));
        out.push('\n');
    }

    if report.metrics_enabled {
        out.push_str("--- Metrics ---\n");
        out.push_str("Cyclomatic complexity feature is active.\n");
    }

    out.push_str(&format!("\nGenerated by gitinspector-rs v{} in {}\n", report.version, report.duration));

    out
}
