# gitinspector-rs mermaid config
layout: elk
fontFamily: "var(--mermaid-font-family)"
elk:
  mergeEdges: true
  nodePlacementStrategy: NETWORK_SIMPLEX
theme: neutral
themeVariables:
  fontFamily: "var(--mermaid-font-family)"
  fontSize: "var(--mermaid-font-size)"
logLevel: fatal
darkMode: false
markdownAutoWrap: true

# Custom Plugin Options
katlas:
  dualRender: true
